#!/usr/bin/env python3
"""
Phase 3 — Build Tag_Dictionary.md from the tag cache.

Outputs:
  - Summary statistics table (sorted by frequency)
  - Per-tag file link sections
  - Untagged files list with clickable titles

Quartz v5 compatible: uses [title](path) standard links (no wikilinks).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


# ── Helpers ───────────────────────────────────────────────────────────────────

def quartz_link(title: str, rel_path: str) -> str:
    """Return a Quartz v5 compatible Markdown link (no .md extension)."""
    slug = re.sub(r"\.md$", "", rel_path)
    # Escape pipe chars that break Markdown tables
    safe_title = title.replace("|", "｜").replace("[", "（").replace("]", "）")
    return f"[{safe_title}]({slug})"


def tag_link(tag: str) -> str:
    """
    Return a tag link compatible with both Obsidian and Quartz v5.

    Format: [#tag](tags/tagname)
    - Quartz v5: navigates to /tags/tagname (shows all docs with that tag)
    - Obsidian:  navigates to tags/tagname path; inline #tag text also styled as tag
    """
    tagname = tag.lstrip("#")
    return f"[{tag}](tags/{tagname})"



def load_cache(cache_path: Path) -> dict:
    try:
        return json.loads(cache_path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[error] Cannot read cache: {e}", file=sys.stderr)
        sys.exit(1)


# ── Builder ───────────────────────────────────────────────────────────────────

def build_dictionary(cache: dict, output_path: Path, repo_root: Path) -> None:
    files: dict = cache.get("files", {})
    tag_index: dict = cache.get("tag_index", {})
    stats: dict = cache.get("stats", {})
    last_scan: str = cache.get("last_scan", "")

    now_str = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M %Z")
    scan_date = last_scan[:10] if last_scan else now_str[:10]

    total = stats.get("total", len(files))
    tagged = stats.get("tagged", 0)
    untagged_count = stats.get("untagged", total - tagged)
    unique_tags = len(tag_index)

    # Sort tags by file count (desc), then alphabetically
    sorted_tags = sorted(
        tag_index.items(),
        key=lambda kv: (-len(kv[1]), kv[0]),
    )

    # Collect untagged files
    untagged_files = [
        (rel, meta)
        for rel, meta in sorted(files.items())
        if not meta.get("has_tags")
    ]

    lines: list[str] = []

    # ── Frontmatter ──────────────────────────────────────────────────────────
    lines += [
        "---",
        "title: Tag Dictionary",
        f"updated: {now_str}",
        f"scanned_files: {total}",
        f"tagged_files: {tagged}",
        f"untagged_files: {untagged_count}",
        "generated_by: /add-tags",
        "tags: #generated #index #tag-dictionary",
        "---",
        "",
    ]

    # ── Header ───────────────────────────────────────────────────────────────
    lines += [
        "# Tag Dictionary",
        "",
        f"> **업데이트**: {now_str} | "
        f"**스캔**: {total}개 파일 | "
        f"**태그 있음**: {tagged} | "
        f"**태그 없음**: {untagged_count} | "
        f"**고유 태그**: {unique_tags}개",
        "",
        "---",
        "",
    ]

    # ── Tag Statistics Table ──────────────────────────────────────────────────
    lines += [
        "## Tag Statistics",
        "",
        f"> 총 {unique_tags}개 고유 태그 — 빈도순 정렬.",
        "",
        "| # | 태그 | 파일 수 |",
        "|---|------|---------|",
    ]

    for rank, (tag, file_paths) in enumerate(sorted_tags, 1):
        lines.append(f"| {rank} | {tag_link(tag)} | {len(file_paths)} |")

    lines += ["", "---", ""]

    # ── Untagged Files ────────────────────────────────────────────────────────
    lines += [
        f"## 태그 없는 파일 ({untagged_count}개)",
        "",
    ]

    if untagged_files:
        lines += [
            "| 생성일 | 제목 | 경로 |",
            "|-------|------|------|",
        ]
        for rel, meta in untagged_files:
            title = meta.get("title", Path(rel).stem)
            created = meta.get("created", "")[:10] or "—"
            link = quartz_link(title, rel)
            dir_part = str(Path(rel).parent)
            lines.append(f"| {created} | {link} | `{dir_part}` |")
    else:
        lines.append("> ✅ 모든 파일에 태그가 있습니다.")

    lines += [
        "",
        "---",
        "",
        f"*Generated by `/add-tags` on {now_str}*",
    ]

    # ── Write output ──────────────────────────────────────────────────────────
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Build Tag_Dictionary.md from cache.")
    parser.add_argument("--output-dir", default=None,
                        help="Directory for Tag_Dictionary.md (env: ADD_TAGS_OUTPUT_DIR)")
    parser.add_argument("--filename", default=None,
                        help="Output filename (env: ADD_TAGS_FILENAME, default: Tag_Dictionary.md)")
    parser.add_argument("--cache-dir", default=None)
    parser.add_argument("--repo-root", default=None)
    args = parser.parse_args()

    script_dir = Path(__file__).parent.parent

    try:
        import subprocess
        repo_root = (
            Path(args.repo_root)
            if args.repo_root
            else Path(subprocess.run(
                ["git", "rev-parse", "--show-toplevel"],
                capture_output=True, text=True, check=True
            ).stdout.strip())
        )
    except Exception:
        print("[error] Could not determine repo root.", file=sys.stderr)
        sys.exit(1)

    cache_dir = Path(args.cache_dir) if args.cache_dir else script_dir / ".cache"
    cache_path = cache_dir / "tag_cache.json"

    # Resolve output path
    output_dir_str = (
        args.output_dir
        or os.environ.get("ADD_TAGS_OUTPUT_DIR")
        or "00_INBOX"
    )
    filename = (
        args.filename
        or os.environ.get("ADD_TAGS_FILENAME")
        or "Tag_Dictionary.md"
    )

    if Path(output_dir_str).is_absolute():
        output_dir = Path(output_dir_str)
    else:
        output_dir = repo_root / output_dir_str

    output_path = output_dir / filename

    # Load cache and build
    cache = load_cache(cache_path)
    build_dictionary(cache, output_path, repo_root)

    stats = cache.get("stats", {})
    print(
        f"  Dictionary: {stats.get('total', '?')} files → {output_path.relative_to(repo_root)}"
    )


if __name__ == "__main__":
    main()
